import { randomUUID } from 'crypto';
import User from '../../modules/hr-core/users/models/user.model.js';
import bcrypt from 'bcryptjs';

describe('User Model', () => {
  it('should create and save a user successfully', async () => {
    const userData = {
      tenantId: 'test_tenant_123',
      username: 'testuser',
      email: 'test@example.com',
      password: 'Password123!',
      role: 'employee',
      personalInfo: {
        firstName: 'Test',
        lastName: 'User',
        phone: '1234567890'
      }
    };

    const user = User.build(userData);
    const savedUser = await user.save();

    expect(savedUser.id).toBeDefined();
    expect(typeof savedUser.id).toBe('string');
    expect(savedUser.username).toBe(userData.username);
    expect(savedUser.email).toBe(userData.email);
    expect(savedUser.role).toBe(userData.role);
    expect(savedUser.personalInfo.firstName).toBe(userData.personalInfo.firstName);
    expect(savedUser.personalInfo.lastName).toBe(userData.personalInfo.lastName);
    expect(savedUser.personalInfo.phone).toBe(userData.personalInfo.phone);
    // Password should be hashed
    expect(savedUser.password).not.toBe(userData.password);
  });

  it('should fail to create a user without required fields', async () => {
    const userData = {
      profile: {
        firstName: 'Test'
      }
    };

    const user = User.build(userData);
    let err;
    try {
      await user.save();
    } catch (error) {
      err = error;
    }

    expect(err).toBeDefined();
    expect(err.errors?.tenantId || err.message).toBeDefined();
    expect(err.errors?.username || err.message).toBeDefined();
    expect(err.errors?.email || err.message).toBeDefined();
    expect(err.errors?.password || err.message).toBeDefined();
  });

  it('should hash user password before saving', async () => {
    const userData = {
      tenantId: 'test_tenant_123',
      username: 'testuser2',
      email: 'test2@example.com',
      password: 'Password123!'
    };

    const user = User.build(userData);
    const savedUser = await user.save();

    // Check that password is hashed
    const isMatch = await bcrypt.compare('Password123!', savedUser.password);
    expect(isMatch).toBe(true);
    expect(savedUser.password).not.toBe(userData.password);
  });

  it('should generate employeeId for new users', async () => {
    const userData = {
      tenantId: 'test_tenant_123',
      username: 'testuser3',
      email: 'test3@example.com',
      password: 'Password123!'
    };

    const user = User.build(userData);
    const savedUser = await user.save();

    expect(savedUser.employeeId).toBeDefined();
    // EmployeeId format: EMID-YYYY-NNNN (auto-generated by hook)
    expect(savedUser.employeeId).toMatch(/^EMID-\d{4}-\d{4}$/);
  });

  it('should compare password correctly', async () => {
    const userData = {
      tenantId: 'test_tenant_123',
      username: 'testuser4',
      email: 'test4@example.com',
      password: 'Password123!'
    };

    const user = User.build(userData);
    const savedUser = await user.save();

    const isMatch = await savedUser.comparePassword('Password123!');
    expect(isMatch).toBe(true);
    expect(await savedUser.comparePassword('WrongPassword')).toBe(false);
  });

  it('should get full name from personalInfo', async () => {
    const userData = {
      tenantId: 'test_tenant_123',
      username: 'testuser5',
      email: 'test5@example.com',
      password: 'Password123!',
      personalInfo: {
        firstName: 'John',
        lastName: 'Doe'
      }
    };

    const user = User.build(userData);
    const savedUser = await user.save();

    expect(savedUser.getFullName()).toBe('John Doe');
  });
});
