#!/usr/bin/env node

/**
 * Generate Proper License Tokens Script
 * 
 * This script creates proper license tokens using the license server API
 * to resolve the algorithm mismatch issue
 */

import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import axios from 'axios';
import Tenant from './models/Tenant.js';

// Get current directory for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from the root directory
dotenv.config({ path: join(__dirname, '..', '.env') });

console.log('🔧 Starting proper license token generation script...');

const LICENSE_SERVER_URL = process.env.LICENSE_SERVER_URL || 'http://localhost:4000';
// Use the admin API key for license creation (from license server output)
const LICENSE_SERVER_API_KEY = 'hrsm_dev_admin_key_1234567890123456789012345678901234567890123';

// Create license via license server API
async function createLicenseViaAPI(tenantData) {
    try {
        const response = await axios.post(`${LICENSE_SERVER_URL}/licenses/create`, {
            tenantId: tenantData.tenantId,
            tenantName: tenantData.name,
            type: 'enterprise',
            modules: [
                'hr-core',
                'tasks',
                'clinic',
                'payroll',
                'reports',
                'life-insurance'
            ],
            maxUsers: 1000,
            maxStorage: 10240, // 10GB in MB (changed from bytes)
            maxAPICallsPerMonth: 1000000,
            expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 year
            maxActivations: 3,
            notes: 'Generated by license token fix script'
        }, {
            headers: {
                'Content-Type': 'application/json',
                'X-API-Key': LICENSE_SERVER_API_KEY
            }
        });

        return response.data;
    } catch (error) {
        console.error(`Failed to create license for ${tenantData.tenantId}:`, error.response?.data || error.message);
        throw error;
    }
}

async function generateProperLicenseTokens() {
    try {
        console.log('🔧 Generating proper license tokens for existing tenants...\n');

        // Connect to MongoDB
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        // Check if license server is running
        try {
            await axios.get(`${LICENSE_SERVER_URL}/health`);
            console.log('✅ License server is running');
        } catch (error) {
            console.error('❌ License server is not running. Please start it first.');
            console.error('Run: cd hrsm-license-server && npm start');
            process.exit(1);
        }

        // Find all tenants with valid tenant IDs
        const tenants = await Tenant.find({
            tenantId: { $exists: true, $ne: null, $ne: '' }
        });
        console.log(`📋 Found ${tenants.length} tenants\n`);

        if (tenants.length === 0) {
            console.log('✅ No tenants found');
            return;
        }

        // Update each tenant with a proper license token
        let successCount = 0;
        let errorCount = 0;

        for (const tenant of tenants) {
            console.log(`🏢 Processing tenant: ${tenant.name} (${tenant.tenantId})`);

            try {
                // Create license via license server API
                const licenseResponse = await createLicenseViaAPI(tenant);
                
                if (licenseResponse.success) {
                    const licenseData = licenseResponse.data;
                    
                    // Update tenant with proper license information
                    const result = await Tenant.findByIdAndUpdate(tenant._id, {
                        $set: {
                            'license.licenseKey': licenseData.token,
                            'license.licenseNumber': licenseData.licenseNumber,
                            'license.licenseType': licenseData.type,
                            'license.licenseStatus': licenseData.status,
                            'license.expiresAt': new Date(licenseData.expiresAt),
                            'license.licenseExpiresAt': new Date(licenseData.expiresAt),
                            'license.activatedAt': new Date(),
                            'license.lastValidatedAt': new Date(),
                            'license.features': [
                                'hr-core',
                                'tasks',
                                'clinic',
                                'payroll',
                                'reports',
                                'life-insurance'
                            ],
                            'license.limits': {
                                maxUsers: 1000,
                                maxStorage: 10 * 1024 * 1024 * 1024, // 10GB in bytes
                                maxAPICallsPerMonth: 1000000
                            }
                        }
                    }, { new: true });

                    if (result) {
                        console.log(`   ✅ Added proper license token (License: ${licenseData.licenseNumber})`);
                        console.log(`   📅 Expires: ${new Date(licenseData.expiresAt).toDateString()}`);
                        successCount++;
                    } else {
                        console.log(`   ❌ Failed to update tenant ${tenant.tenantId}`);
                        errorCount++;
                    }
                } else {
                    console.log(`   ❌ License server returned error: ${licenseResponse.error}`);
                    errorCount++;
                }
            } catch (error) {
                console.log(`   ❌ Error: ${error.message}`);
                errorCount++;
            }
        }

        console.log(`\n🎉 Processing completed:`);
        console.log(`   ✅ Success: ${successCount} tenants`);
        console.log(`   ❌ Errors: ${errorCount} tenants`);

        // Verify the updates
        const updatedTenants = await Tenant.find({
            'license.licenseKey': { $exists: true, $ne: null, $ne: '' }
        });

        console.log(`\n📊 Verification: ${updatedTenants.length} tenants now have license tokens`);

        // Show sample tenant license info
        if (updatedTenants.length > 0) {
            const sampleTenant = updatedTenants.find(t => t.tenantId === 'techcorp_solutions') || updatedTenants[0];
            console.log(`\n📋 Sample license info for ${sampleTenant.name}:`);
            console.log(`   Tenant ID: ${sampleTenant.tenantId}`);
            console.log(`   License Number: ${sampleTenant.license.licenseNumber}`);
            console.log(`   License Type: ${sampleTenant.license.licenseType}`);
            console.log(`   Status: ${sampleTenant.license.licenseStatus}`);
            console.log(`   Expires: ${sampleTenant.license.expiresAt?.toDateString()}`);
            console.log(`   Features: ${sampleTenant.license.features?.length || 0} modules`);
            console.log(`   Max Users: ${sampleTenant.license.limits?.maxUsers || 'N/A'}`);
            console.log(`   Token (first 50 chars): ${sampleTenant.license.licenseKey?.substring(0, 50)}...`);
        }

    } catch (error) {
        console.error('❌ Error generating proper license tokens:', error.message);
        console.error(error.stack);
        process.exit(1);
    } finally {
        await mongoose.disconnect();
        console.log('\n🔌 Disconnected from MongoDB');
    }
}

// Run the script
console.log('🚀 Running proper license token generation...');
generateProperLicenseTokens()
    .then(() => {
        console.log('\n✅ Proper license token generation completed successfully');
        process.exit(0);
    })
    .catch((error) => {
        console.error('\n❌ Proper license token generation failed:', error.message);
        console.error(error.stack);
        process.exit(1);
    });

export default generateProperLicenseTokens;