import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

console.log('🚀 Starting TechCorp Attendance Upload...');

// Simple attendance schema without complex imports
const attendanceSchema = new mongoose.Schema({
    tenantId: { type: String, required: true, index: true },
    employee: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    department: { type: mongoose.Schema.Types.ObjectId, ref: 'Department', index: true },
    position: { type: mongoose.Schema.Types.ObjectId, ref: 'Position' },
    date: { type: Date, required: true },
    schedule: {
        startTime: { type: String, default: '09:00' },
        endTime: { type: String, default: '17:00' },
        expectedHours: { type: Number, default: 8 }
    },
    checkIn: {
        time: Date,
        method: { type: String, enum: ['biometric', 'manual', 'wfh'] },
        location: { type: String, enum: ['office', 'home', 'remote'] },
        isLate: { type: Boolean, default: false },
        lateMinutes: { type: Number, default: 0 }
    },
    checkOut: {
        time: Date,
        method: { type: String, enum: ['biometric', 'manual', 'wfh'] },
        location: { type: String, enum: ['office', 'home', 'remote'] },
        isEarly: { type: Boolean, default: false },
        earlyMinutes: { type: Number, default: 0 }
    },
    hours: {
        actual: { type: Number, default: 0 },
        expected: { type: Number, default: 8 },
        overtime: { type: Number, default: 0 },
        workFromHome: { type: Number, default: 0 },
        totalHours: { type: Number, default: 0 }
    },
    workFromHome: {
        isWFH: { type: Boolean, default: false },
        approved: { type: Boolean, default: false },
        approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        reason: String
    },
    status: {
        type: String,
        enum: ['on-time', 'late', 'present', 'absent', 'vacation', 'sick-leave', 'mission', 'work-from-home', 'half-day', 'official-holiday', 'weekend', 'early-departure', 'forgot-check-in', 'forgot-check-out'],
        default: 'absent'
    },
    source: { type: String, enum: ['biometric', 'cloud', 'mobile', 'qr', 'manual', 'csv', 'system'], default: 'system' },
    flags: {
        isLate: { type: Boolean, default: false },
        isEarlyDeparture: { type: Boolean, default: false },
        isMissing: { type: Boolean, default: false },
        needsApproval: { type: Boolean, default: false }
    },
    notes: String,
    isWorkingDay: { type: Boolean, default: true },
    autoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

// Compound indexes for tenant isolation
attendanceSchema.index({ tenantId: 1, employee: 1, date: 1 }, { unique: true });

const Attendance = mongoose.model('Attendance', attendanceSchema);

// User schema
const userSchema = new mongoose.Schema({
    tenantId: { type: String, required: true },
    username: { type: String, required: true },
    email: { type: String, required: true },
    employeeId: { type: String, required: true },
    status: { type: String, default: 'active' },
    personalInfo: {
        firstName: String,
        lastName: String
    },
    department: { type: mongoose.Schema.Types.ObjectId, ref: 'Department' },
    position: { type: mongoose.Schema.Types.ObjectId, ref: 'Position' }
});

const User = mongoose.model('User', userSchema);

// Company schema (platform_companies collection)
const companySchema = new mongoose.Schema({
    name: { type: String, required: true },
    slug: { type: String, required: true, unique: true }
});

const Company = mongoose.model('Company', companySchema, 'platform_companies');

/**
 * Generate random time within a range
 */
function getRandomTime(baseHour, baseMinute, varianceMinutes = 30) {
    const variance = Math.floor(Math.random() * varianceMinutes * 2) - varianceMinutes;
    const totalMinutes = baseHour * 60 + baseMinute + variance;
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}`;
}

/**
 * Create attendance record for a specific date and employee
 */
function createAttendanceRecord(employee, date, tenantId) {
    const dayOfWeek = date.getDay(); // 0 = Sunday, 6 = Saturday
    
    // Skip weekends (Friday and Saturday)
    if (dayOfWeek === 5 || dayOfWeek === 6) {
        return null;
    }

    // Random chance of absence (5%)
    if (Math.random() < 0.05) {
        return new Attendance({
            tenantId,
            employee: employee._id,
            department: employee.department,
            position: employee.position,
            date: new Date(date),
            status: 'absent',
            isWorkingDay: true,
            autoGenerated: true,
            schedule: {
                startTime: '09:00',
                endTime: '17:00',
                expectedHours: 8
            },
            hours: {
                actual: 0,
                expected: 8,
                overtime: 0,
                workFromHome: 0,
                totalHours: 0
            }
        });
    }

    // Random chance of work from home (10%)
    const isWFH = Math.random() < 0.1;
    
    // Generate check-in time (8:30 - 9:30 AM)
    const checkInTime = getRandomTime(9, 0, 60); // 8:00 - 10:00 AM
    const [checkInHour, checkInMinute] = checkInTime.split(':').map(Number);
    
    // Generate check-out time (4:30 - 6:30 PM)
    const checkOutTime = getRandomTime(17, 30, 120); // 3:30 - 7:30 PM
    const [checkOutHour, checkOutMinute] = checkOutTime.split(':').map(Number);
    
    // Create Date objects for check-in and check-out
    const checkInDate = new Date(date);
    checkInDate.setHours(checkInHour, checkInMinute, 0, 0);
    
    const checkOutDate = new Date(date);
    checkOutDate.setHours(checkOutHour, checkOutMinute, 0, 0);
    
    // Calculate actual hours worked
    const hoursWorked = (checkOutDate - checkInDate) / (1000 * 60 * 60);
    const expectedHours = 8;
    const overtime = Math.max(0, hoursWorked - expectedHours);
    
    // Determine if late (after 9:15 AM)
    const isLate = checkInHour > 9 || (checkInHour === 9 && checkInMinute > 15);
    const lateMinutes = isLate ? Math.max(0, (checkInHour - 9) * 60 + (checkInMinute - 15)) : 0;
    
    // Determine if early departure (before 4:30 PM)
    const isEarly = checkOutHour < 16 || (checkOutHour === 16 && checkOutMinute < 30);
    const earlyMinutes = isEarly ? Math.max(0, (16 * 60 + 30) - (checkOutHour * 60 + checkOutMinute)) : 0;
    
    // Determine status
    let status = 'present';
    if (isWFH) {
        status = 'work-from-home';
    } else if (isLate && !isEarly) {
        status = 'late';
    } else if (isEarly && !isLate) {
        status = 'early-departure';
    } else if (!isLate && !isEarly) {
        status = 'on-time';
    }

    return new Attendance({
        tenantId,
        employee: employee._id,
        department: employee.department,
        position: employee.position,
        date: new Date(date),
        schedule: {
            startTime: '09:00',
            endTime: '17:00',
            expectedHours: 8
        },
        checkIn: {
            time: checkInDate,
            method: isWFH ? 'wfh' : 'biometric',
            location: isWFH ? 'home' : 'office',
            isLate,
            lateMinutes
        },
        checkOut: {
            time: checkOutDate,
            method: isWFH ? 'wfh' : 'biometric',
            location: isWFH ? 'home' : 'office',
            isEarly,
            earlyMinutes
        },
        hours: {
            actual: isWFH ? 0 : hoursWorked,
            expected: expectedHours,
            overtime,
            workFromHome: isWFH ? hoursWorked : 0,
            totalHours: hoursWorked
        },
        workFromHome: {
            isWFH,
            approved: isWFH,
            approvedBy: null,
            reason: isWFH ? 'Remote work day' : null
        },
        status,
        source: 'system',
        flags: {
            isLate,
            isEarlyDeparture: isEarly,
            isMissing: false,
            needsApproval: false
        },
        isWorkingDay: true,
        autoGenerated: true
    });
}

/**
 * Upload attendance data for TechCorp Solutions
 */
async function uploadTechCorpAttendance() {
    try {
        console.log('🔌 Connecting to MongoDB...');
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        // Find TechCorp Solutions company
        const company = await Company.findOne({ slug: 'techcorp_solutions' });
        if (!company) {
            throw new Error('TechCorp Solutions company not found');
        }

        console.log(`\n🏢 Found TechCorp Solutions company:`);
        console.log(`  ID: ${company._id}`);
        console.log(`  Name: ${company.name}`);

        // Find all active users for TechCorp Solutions
        const users = await User.find({
            tenantId: company._id.toString(),
            status: 'active'
        });

        console.log(`\n👥 Found ${users.length} active users for TechCorp Solutions`);

        // Generate attendance for the past 30 days
        const endDate = new Date();
        const startDate = new Date();
        startDate.setDate(startDate.getDate() - 30);

        console.log(`\n📅 Generating attendance records from ${startDate.toDateString()} to ${endDate.toDateString()}`);

        let totalRecords = 0;
        let createdRecords = 0;
        let skippedRecords = 0;

        // Process each user
        for (const user of users) {
            console.log(`\n👤 Processing attendance for ${user.personalInfo?.firstName || 'Unknown'} ${user.personalInfo?.lastName || ''} (${user.employeeId})`);
            
            let userRecords = 0;
            
            // Generate attendance for each day
            for (let date = new Date(startDate); date <= endDate; date.setDate(date.getDate() + 1)) {
                const currentDate = new Date(date);
                totalRecords++;

                // Check if attendance record already exists
                const existingRecord = await Attendance.findOne({
                    tenantId: company._id.toString(),
                    employee: user._id,
                    date: {
                        $gte: new Date(currentDate.setHours(0, 0, 0, 0)),
                        $lt: new Date(currentDate.setHours(23, 59, 59, 999))
                    }
                });

                if (existingRecord) {
                    skippedRecords++;
                    continue;
                }

                // Create attendance record
                const attendanceRecord = createAttendanceRecord(user, currentDate, company._id.toString());
                
                if (attendanceRecord) {
                    try {
                        await attendanceRecord.save();
                        createdRecords++;
                        userRecords++;
                    } catch (error) {
                        console.error(`  ❌ Error saving attendance for ${currentDate.toDateString()}: ${error.message}`);
                    }
                }
            }
            
            console.log(`  ✅ Created ${userRecords} attendance records`);
        }

        console.log(`\n📊 Attendance Upload Summary:`);
        console.log(`  Total records processed: ${totalRecords}`);
        console.log(`  Records created: ${createdRecords}`);
        console.log(`  Records skipped (already exist): ${skippedRecords}`);
        console.log(`  Success rate: ${((createdRecords / Math.max(1, totalRecords - skippedRecords)) * 100).toFixed(1)}%`);

        // Generate some statistics
        const attendanceStats = await Attendance.aggregate([
            {
                $match: {
                    tenantId: company._id.toString(),
                    date: { $gte: startDate, $lte: endDate }
                }
            },
            {
                $group: {
                    _id: '$status',
                    count: { $sum: 1 },
                    totalHours: { $sum: '$hours.totalHours' }
                }
            },
            {
                $sort: { count: -1 }
            }
        ]);

        console.log(`\n📈 Attendance Statistics:`);
        attendanceStats.forEach(stat => {
            console.log(`  ${stat._id}: ${stat.count} records (${stat.totalHours.toFixed(1)} total hours)`);
        });

        console.log('\n✅ Attendance upload completed successfully!');

    } catch (error) {
        console.error('❌ Error uploading attendance:', error);
        throw error;
    } finally {
        console.log('\n🔌 Disconnecting from MongoDB...');
        await mongoose.disconnect();
        console.log('✅ Disconnected from MongoDB');
    }
}

// Run the upload
uploadTechCorpAttendance()
    .then(() => {
        console.log('\n🎉 Attendance upload process completed!');
        process.exit(0);
    })
    .catch((error) => {
        console.error('\n💥 Attendance upload failed:', error);
        process.exit(1);
    });