/**
 * Error Type Constants
 * 
 * Centralized error codes for consistent error handling across the application
 * Organized by layer: Platform, Tenant, Module, Authentication, and Validation
 */

// Platform Layer Errors (5xx)
export const PLATFORM_ERRORS = {
    PLATFORM_INITIALIZATION_ERROR: 'PLATFORM_INITIALIZATION_ERROR',
    PLATFORM_DATABASE_ERROR: 'PLATFORM_DATABASE_ERROR',
    SYSTEM_CONFIGURATION_ERROR: 'SYSTEM_CONFIGURATION_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

// Tenant Layer Errors (4xx)
export const TENANT_ERRORS = {
    TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
    TENANT_SUSPENDED: 'TENANT_SUSPENDED',
    TENANT_CANCELLED: 'TENANT_CANCELLED',
    TENANT_QUOTA_EXCEEDED: 'TENANT_QUOTA_EXCEEDED',
    TENANT_INACTIVE: 'TENANT_INACTIVE',
    INVALID_TENANT_ID: 'INVALID_TENANT_ID'
};

// Module Layer Errors (4xx)
export const MODULE_ERRORS = {
    MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
    MODULE_DISABLED: 'MODULE_DISABLED',
    MODULE_DEPENDENCY_MISSING: 'MODULE_DEPENDENCY_MISSING',
    MODULE_LOAD_FAILED: 'MODULE_LOAD_FAILED',
    MODULE_INITIALIZATION_ERROR: 'MODULE_INITIALIZATION_ERROR'
};

// Authentication Errors (401)
export const AUTH_ERRORS = {
    INVALID_PLATFORM_TOKEN: 'INVALID_PLATFORM_TOKEN',
    INVALID_TENANT_TOKEN: 'INVALID_TENANT_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS'
};

// Validation Errors (400)
export const VALIDATION_ERRORS = {
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_FORMAT: 'INVALID_FORMAT'
};

// General Errors
export const GENERAL_ERRORS = {
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    BAD_REQUEST: 'BAD_REQUEST',
    FORBIDDEN: 'FORBIDDEN'
};

// Export all error types as a single object
export const ERROR_TYPES = {
    ...PLATFORM_ERRORS,
    ...TENANT_ERRORS,
    ...MODULE_ERRORS,
    ...AUTH_ERRORS,
    ...VALIDATION_ERRORS,
    ...GENERAL_ERRORS
};

export default ERROR_TYPES;
